# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
addons:
  apt:
    packages:
    - librsvg2-bin
julia:
  - 1.0
  - 1
  - nightly
notifications:
  email: false
jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
  include:
    - stage: Documentation
      julia: 1
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
